### ISSUE TITLE
How can i set selected value

### ISSUE THREAD

**Issue by furucrm-jack** [pozil/sfdc-ui-lookup#10]
I want to 
1. get contact id from URL param
2. fetch contact data from controller
3. set contact from step 2 to ur custom lookup
I don't know how to achieve step 3, can u guide me ? thank you so much

**Comment by furucrm-jack** [comment]
I did it myself.

**Comment by Alexandra281989** [comment]
jackfurucrm, how did you do it?

**Comment by furucrm-jack** [comment]
> jackfurucrm, how did you do it?

1. create a method in your apex controller return List< LookupSearchResult > query for your specific id
2. set return value from step 1 above to {!v.selection} on init of SampleLookupContainer.cmp

**Comment by Alexandra281989** [comment]
Hello  jackfurucrm,

Can you please send me a print screen with your code? Sorry, but I'm a
beginner and it is not entirely clear to me. :( Thanks!

În mie., 24 apr. 2019 la 10:18, jackfurucrm <notifications@github.com> a
scris:

**Comment by furucrm-jack** [comment]
> Hello jackfurucrm, Can you please send me a print screen with your code? Sorry, but I'm a beginner and it is not entirely clear to me. :( Thanks!

sure, give me ur email. I'll try to help you.

**Comment by Alexandra281989** [comment]
andrica.alexandra@gmail.com Thank you so much!

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 24, 2019 at 10:29, jackfurucrm<notifications@github.com> wrote:   

Hello jackfurucrm, Can you please send me a print screen with your code? Sorry, but I'm a beginner and it is not entirely clear to me. :( Thanks!


sure, give me ur email. I'll try to help you.
