### ISSUE TITLE
RecordId

### ISSUE THREAD

**Issue by Alexandra281989** [pozil/sfdc-ui-lookup#13]
Hello,

If I include the lookup component on the Account page, how can I transmit the Account Id to the Apex controller? I want to save the selected opportunities.Thanks

**Comment by pozil** [comment]
Hi @Alexandra281989, I saw your comments in issue #10.
Are you all set?

**Comment by akankshakapse** [comment]
I am also having same query. Can you please guide. I am adding multiple lookups in a same form (bulk update page). How to get selected record id in save details. Please help.

**Comment by pozil** [comment]
Hi @akankshakapse,

You shouldn't need to modify the lookup component itself, just the container.
Here's what you should do to make this work (I haven't tested though).

Assuming that `SampleLookupContainer` has a `recordId` attribute that is set with the right value.

**Modify SampleLookupContainerController.js**
Add the record id as a parameter of the search action that you pass to the lookup.

```js
lookupSearch : function(component, event, helper) {
  // Get the SampleLookupController.search server side action
  const serverSearchAction = component.get('c.search');

  // Add the record id to the search action before passing it to the lookup
  serverSearchAction.setParams({
    recordId: component.get('v.recordId');
  });

  // Passes the action to the Lookup component by calling the search method
  component.find('lookup').search(serverSearchAction);
},
```

**Modify SampleLookupController.cls**
Add `recordId` to the signature of the search method.

```apex
@AuraEnabled(cacheable=true)
public static List<LookupSearchResult> search(String recordId, String searchTerm, List<String> selectedIds) {

  // Rest of the code...
}
```

Let me know if that helps.

**Comment by pozil** [comment]
Hi, I made changes to support this scenario and documented that use case.
I am closing the issue for now, let me know if you need further assistance.

**Comment by akankshakapse** [comment]
Hi,
Sorry for the late reply.

Thanks a lot for your suggestion and updates. As of now this
functionality is on hold.
Thanks!!
