### ISSUE TITLE
Multiple instances of Lookup component

### ISSUE THREAD

**Issue by AlexSolo2019** [pozil/sfdc-ui-lookup#14]
Hello,

i inserted the Lookup component as a single-entry combobox into an own component.
I have no problems working with single field, but the Lookup component is in an iterator.

.....
<tbody>
<aura:iteration items="{!v.rows}" var="row" indexVar="index">
    <tr>
        <td>
			<c:Lookup aura:id="lookup"
                   	selection="{!row.selection}"
                   	onSearch="{!c.lookupSearch}" 
                   	onSelection="{!c.onSubmit}"  
                   	disabled="{! !empty(row.selection)}"
                   	filter="{!$Label.c.ProductRecordTypeId}"
                   	placeholder="Productname..."
                    isMultiEntry="{!v.isMultiEntry}"/>
		</td>
	</tr>
</aura:iteration>
</tbody>
....

From second and further iterator i have the following problem:
	- the Lookup component cann't retrieve an index, i.e. i can't set a focus on field or clean the field

Would you help me to solve this problem? Thanks.

**Comment by pozil** [comment]
Hi @AlexSolo2019, I'm sorry but I didn't understand your ask.
Can you include some sample code or rephrase to give me a bit more context?

**Comment by AlexSolo2019** [comment]
Hello pozil, so that you could understand correctly, I have added a screenshot:

![grafik](https://user-images.githubusercontent.com/53224648/61850828-85495500-aeb5-11e9-829b-f478a229b500.png)

I would like to explain my problem again. The Lookup instance resides in an iterator, 
which means it can be multiple Lookup instances. The onFocus and onClick events of each 
Lookup instance should differentiate in which Lookup instance this happens. 
My question: how can I do this? 

Thank you in advance.

**Comment by pozil** [comment]
Hi @AlexSolo2019,

What `onFocus` and `onClick` events are you referring to? The lookup doesn't expose those, do you mean `onSelection` and `onSearch`?

If so, looking at your code, I see that all of your lookup components are going to have the same `aura:id` value. This means that you can't use `component.find` to retrieve a specific lookup like I did earlier the sample code.

Since that won't work, I've updated the sample code to the following elegant solution:
```js
lookupSearch : function(component, event, helper) {
  // Get the lookup component that fired the search event
  const lookupComponent = event.getSource();
  // Get the Apex server-side action associated with this search (`search` in our samples)
  const serverSearchAction = component.get('c.search');
  // Passes the action to the lookup component by calling the `search` aura method
  lookupComponent.search(serverSearchAction);
}
```

By retrieving the lookup with `event.getSource()`, we no longer need a unique `aura:id` on the lookup.
That should solve your iteration issue, right?

**Comment by AlexSolo2019** [comment]
Hello pozil,
i solved that a little bit differently:

lookupSearch : function(component, event, helper) {
     const serverSearchAction = component.get('c.search'); 
     const components = component.find("lookup");
       
     if(components.length == null) { // One component only
            component.find("lookup").search(serverSearchAction);
     } else { // Several components
           var index = component.get('v.selectedRowIndex');
            components[index].search(serverSearchAction);
      }
   }

The problem is how my module can read an index on onClick event from the lookup component. The lookup component consists of five objects:
- lightning: icon for picture
- input tag
- spinner
- lightning: icon for searches
- lightning: icon for cleaning

The last object has an onClick event that I want to intercept in my module. Is that possible? 
Thank you in advance.

**Comment by pozil** [comment]
Hi @AlexSolo2019,

If I understand correctly your need, you want to have different search actions depending on the selected lookups and different actions when the selection changes.

I advise you not to fork the Lookup component or use the code you mentioned for those use cases.
Instead, use the Lookup's latest version and wrap it in a `div` with a dynamic dataset attribute like so:
```xml
<div data-row-index="{!v.rowIndex}">
  <c:Lookup .../>
</div>
```

Then, in your search function, simply do that:
```js
// Get the lookup component that fired the search event
const lookupComponent = event.getSource();
// Get the row index from the parent div
const rowIndex = lookupComponent.getElement().parentNode.dataset.rowIndex;
alert('Row index: '+ rowIndex);

// Handle the rest of the search logic
// You can use different search endpoints depending on the row index for example
```

I hope this helps.

**Comment by AlexSolo2019** [comment]
Thank you
