### ISSUE TITLE
Event as a component attribute

### ISSUE THREAD

**Issue by banderson5144** [pozil/sfdc-ui-lookup#2]
https://github.com/pozil/sfdc-ui-lookup/blob/16f5daf82fc51dbd4e055305c1a79c9b578927c2/src-sample/main/default/aura/SampleLookupContainer/SampleLookupContainer.cmp#L5

@pozil I really like this event handler implementation you did here, instead of using the traditional `<aura:handler>`. Is there anywhere this style is documented?

**Comment by pozil** [comment]
Thanks for the feedback.

I struggled a bit to find an example in the official docs but here it is:
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/events_component_handling_child.htm
