### ISSUE TITLE
updateSearchTerm string replacement bug

### ISSUE THREAD

**Issue by no-stack-dub-sack** [pozil/sfdc-ui-lookup#7]
hi @pozil, I just noticed a small bug in the [updateSearchTerm helper method](https://github.com/pozil/sfdc-ui-lookup/blob/a9157cfabaa838e8fbf202957597f6313f78b078/src/main/default/aura/Lookup/LookupHelper.js#L4). 

It looks like you intended to replace the * character with a space or '', but the current code would result in '* Edge' being transformed into 'undefined edge'. Its probably pretty rare someone would attempt a wildcard search through the UI, but thought it was worth reporting.

**Comment by pozil** [comment]
Good catch, I've fixed it.
Thanks for letting me know.
